### ISSUE TITLE
Action is not committing package-lock.json 

### ISSUE THREAD

**Issue by datenpate** [JasonEtco/npm-audit-fix-action#4]
Running
```
name: Audit npm dependencies

on:
  push:
    branches:
      - master

jobs:
  audit_npm:
    name: Audit npm dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Audit npm dependencies
        uses: JasonEtco/npm-audit-fix-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

is creating a new Pull Request, but without the file change on the "package-lock.json".
